name: Rust Lint

on: [push, pull_request]

jobs:
  clippy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: clippy
        override: true

    - name: Run clippy
      run: make lint
